name: Github to Artifactory OIDC Auth

on:
  workflow_dispatch:

env:
  # הגדרות כלליות לסביבה שלך
  PULL_REPO: 'docker-remote'
  DEV_REPO: 'ronma-heinztest-dev'
  JFROG_PROJECT: 'ronma'
  JFROG_URL: 'https://elinaf.jfrog.io'
  OIDC_PROVIDER: 'fadij'
  DOWNLOAD_REPO: 'jfrog-basecli-remote'

  # הוספה של ריפו ל-PULL ו-DEV (כמו שביקשת)

jobs:
  auth:
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with Artifactory using OIDC
        id: jfrog-auth
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ env.JFROG_URL }}
          JF_PROJECT: ${{ env.JFROG_PROJECT }}
          OIDC_PROVIDER: ${{ env.OIDC_PROVIDER }}
        with:
          oidc-provider-name: ${{ env.OIDC_PROVIDER }}
          oidc-audience: jfrog
          download-repository: ${{ env.DOWNLOAD_REPO }}
          version: 2.74.1

      - name: Debug - Print OIDC Token Claims
        run: |
          echo "=== Raw ID Token ==="
          echo "${{ steps.jfrog-auth.outputs.id_token }}"
          echo ""
          echo "=== Decoded Token Payload ==="
          echo "${{ steps.jfrog-auth.outputs.id_token }}" | cut -d '.' -f2 | base64 -d | jq .

      - name: Debug - Show Repo Vars
        run: |
          echo "Pull Repo: ${{ env.PULL_REPO }}"
          echo "Dev Repo: ${{ env.DEV_REPO }}"
