name: oidc-poc

on:
  workflow_dispatch:

jobs:
  auth:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with Artifactory using OIDC
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://elinaf.jfrog.io
          JF_PROJECT: ronma
          OIDC_PROVIDER: fadij
        with:
          oidc-provider-name: ${{ env.OIDC_PROVIDER }}
          version: 2.74.1

      - name: Debug - Print OIDC Token Claims
        run: |
          echo "Printing OIDC token claims for debugging..."
          echo "ACTIONS_ID_TOKEN_REQUEST_URL: $ACTIONS_ID_TOKEN_REQUEST_URL"
          echo "ACTIONS_ID_TOKEN_REQUEST_TOKEN: $ACTIONS_ID_TOKEN_REQUEST_TOKEN"

      - name: Run JFrog CLI Command
        run: |
          jf -v
