name: Github to Artifactory OIDC Auth

on:
  workflow_dispatch:

env:
  # הגדרות כלליות לסביבה שלך
  PULL_REPO: 'docker-remote'
  DEV_REPO: 'ronma-heinztest-dev'
  JFROG_PROJECT: 'ronma'
  JFROG_URL: 'https://elinaf.jfrog.io'
  OIDC_PROVIDER: 'fadij'
  # הוספה של ריפו ל-PULL ו-DEV (כמו שביקשת)

jobs:
  auth:
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with Artifactory using OIDC
        id: jfrog-auth
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ env.JFROG_URL }}
          JF_PROJECT: "ronma"
          OIDC_PROVIDER: "fadij"
        with:
          oidc-provider-name: ${{ env.OIDC_PROVIDER }}
          version: 2.74.1
      - name: Check JFrog CLI version
        run: jf --version
